// Extremadura wildlife & birding sites
// Centre: La Tierra Verde Holiday Accommodations (SW Cáceres province)

const BASE = {
  name: "La Tierra Verde Holiday Accommodations",
  lat: 39.1610143,
  lng: -6.2515144,
  note: "Your base for exploring Extremadura.",
};

const TYPES = {
  forest:   { label: "Dehesa / Forest",   color: "#3a7d3a" },
  steppe:   { label: "Steppe / Plains",   color: "#c8a23a" },
  wetland:  { label: "Wetland / Lake",    color: "#2a7fb8" },
  mountain: { label: "Mountain",          color: "#7a5a3a" },
  canyon:   { label: "Canyon / Cliffs",   color: "#a04040" },
  town:     { label: "Town wildlife",     color: "#8a4ba0" },
};

const SITES = [
  {
    id: "cornalvo",
    name: "Parque Natural de Cornalvo",
    type: "forest",
    lat: 39.0500,
    lng: -6.2000,
    summary: "Mediterranean dehesa around a 2,000-year-old Roman dam, just south of Mérida.",
    highlights: ["Black vulture", "Spanish imperial eagle", "Otter", "Black stork"],
    bestSeason: "Spring (Mar–May) and autumn",
    durationHours: 3,
    tips: "Park at the visitor centre near Trujillanos; the loop trail to the Roman dam is gentle and excellent for woodland birds and dragonflies.",
    website: "https://parquenaturaldecornalvo.juntaex.es/",
  },
  {
    id: "llanos-caceres",
    name: "Llanos de Cáceres y Sierra de Fuentes (ZEPA)",
    type: "steppe",
    lat: 39.4000,
    lng: -6.3000,
    summary: "Vast pseudo-steppe just east of Cáceres city — Europe's premier site for great bustard and little bustard.",
    highlights: ["Great bustard", "Little bustard", "Pin-tailed sandgrouse", "Black-bellied sandgrouse", "Montagu's harrier"],
    bestSeason: "March–May (bustard lekking) and December–February (sandgrouse flocks)",
    durationHours: 4,
    tips: "Drive the back roads between Santa Marta de Magasca and Monroy at dawn. Stay in the car — it's the best hide. Avoid hot midday hours.",
    website: "",
  },
  {
    id: "trujillo",
    name: "Trujillo town & surrounding plains",
    type: "town",
    lat: 39.4600,
    lng: -5.8800,
    summary: "Medieval hilltop town with hundreds of nesting lesser kestrels, white storks and pallid swifts on the historic buildings.",
    highlights: ["Lesser kestrel", "White stork", "Pallid swift", "Spotless starling", "Black-shouldered kite (plains)"],
    bestSeason: "April–June (breeding colonies active)",
    durationHours: 2,
    tips: "Climb to the castle at sunset for kestrel spectacle. The Belén plains 5 km south hold great bustards and rollers.",
    website: "",
  },
  {
    id: "alcollarin",
    name: "Embalse de Alcollarín",
    type: "wetland",
    lat: 39.2100,
    lng: -5.7000,
    summary: "Reservoir that floods in winter, hosting one of Extremadura's largest common crane roosts.",
    highlights: ["Common crane (winter)", "Black-winged stilt", "Avocet", "Greylag goose", "Marsh harrier"],
    bestSeason: "November–February for cranes; April–May for waders on passage",
    durationHours: 2,
    tips: "Arrive an hour before sunset to watch cranes flying in to roost. The eastern shore has the best viewpoints.",
    website: "",
  },
  {
    id: "hornachos",
    name: "Sierra Grande de Hornachos",
    type: "mountain",
    lat: 38.5500,
    lng: -6.0500,
    summary: "Isolated quartzite ridge rising abruptly from the plains — a stronghold for cliff-nesting raptors.",
    highlights: ["Bonelli's eagle", "Spanish imperial eagle", "Eagle owl", "Egyptian vulture", "Blue rock thrush"],
    bestSeason: "February–June (territorial displays and breeding)",
    durationHours: 4,
    tips: "The miradores above Hornachos village give scope views of cliff faces. Bring a telescope for distant raptor perches.",
    website: "",
  },
  {
    id: "orellana",
    name: "Embalse de Orellana & Sierra de Pela",
    type: "wetland",
    lat: 39.0500,
    lng: -5.5500,
    summary: "Ramsar-listed reservoir paired with steppe hills — a mosaic that combines waterbirds with classic steppe specialists.",
    highlights: ["Greater flamingo", "Black stork (passage)", "Great bustard", "Rufous-tailed scrub robin", "Crane"],
    bestSeason: "Year-round; spring is peak diversity",
    durationHours: 4,
    tips: "Stop at the Puerto Peña dam for raptors over the cliffs, then explore the steppe on the Sierra de Pela road north.",
    website: "",
  },
  {
    id: "la-serena",
    name: "La Serena",
    type: "steppe",
    lat: 38.9000,
    lng: -5.5000,
    summary: "The largest pseudo-steppe in Western Europe — open horizon-to-horizon plains grazed by Merino sheep.",
    highlights: ["Great bustard", "Little bustard", "Pin-tailed sandgrouse", "Black-bellied sandgrouse", "Calandra lark", "Roller"],
    bestSeason: "April–June; cranes use it Nov–Feb",
    durationHours: 5,
    tips: "Use the Castuera–Cabeza del Buey road as a transect. Roads are quiet but exposed — bring water, sun protection, fuel.",
    website: "",
  },
  {
    id: "sierra-san-pedro",
    name: "Sierra de San Pedro (ZEPA)",
    type: "forest",
    lat: 39.4000,
    lng: -6.8500,
    summary: "Wild dehesa and cork-oak ridges — the densest concentration of Spanish imperial eagles and black storks in Spain.",
    highlights: ["Spanish imperial eagle", "Black stork", "Black vulture", "Iberian lynx (occasional)", "Cinereous vulture"],
    bestSeason: "March–June",
    durationHours: 5,
    tips: "The EX-303 road between Membrío and Salorino crosses the heart of the ZEPA. Pull over at miradores; do not enter private fincas.",
    website: "",
  },
  {
    id: "monfrague",
    name: "Parque Nacional de Monfragüe",
    type: "canyon",
    lat: 39.8300,
    lng: -6.0500,
    summary: "Extremadura's flagship national park — a Tagus river canyon ringed by quartzite cliffs holding Europe's densest vulture colonies.",
    highlights: ["Griffon vulture", "Cinereous vulture", "Egyptian vulture", "Black stork", "Spanish imperial eagle", "Eagle owl"],
    bestSeason: "February–June; September for migration",
    durationHours: 6,
    tips: "Start at Villarreal de San Carlos visitor centre. Don't miss the Salto del Gitano viewpoint at any time of day.",
    website: "https://www.turismoextremadura.com/viajar/turismo/en/explore/Monfrague-National-Park/",
  },
  {
    id: "salto-gitano",
    name: "Salto del Gitano (Peñafalcón)",
    type: "canyon",
    lat: 39.8400,
    lng: -6.0470,
    summary: "Iconic 200-metre cliff inside Monfragüe. Stand at the roadside viewpoint and griffon vultures pass at eye level.",
    highlights: ["Griffon vulture (300+ pairs)", "Egyptian vulture", "Black stork", "Blue rock thrush", "Alpine swift"],
    bestSeason: "March–June (breeding cliffs alive)",
    durationHours: 1,
    tips: "Visit early morning for thermal lift-off, or late afternoon for golden light. The car park fills fast on weekends.",
    website: "",
  },
  {
    id: "arrocampo",
    name: "Embalse de Arrocampo",
    type: "wetland",
    lat: 39.8500,
    lng: -5.6500,
    summary: "Power-station cooling reservoir that stays warm year-round — a magnet for herons and rare wetland birds.",
    highlights: ["Purple swamphen", "Little bittern", "Squacco heron", "Purple heron", "Great reed warbler"],
    bestSeason: "April–July",
    durationHours: 3,
    tips: "Five well-signposted hides along the perimeter. Hide 1 (near Saucedilla) is the most productive; bring binoculars and patience.",
    website: "",
  },
  {
    id: "tajo-internacional",
    name: "Parque Natural Tajo Internacional",
    type: "canyon",
    lat: 39.5500,
    lng: -7.3000,
    summary: "The Tagus carves a deep frontier canyon with Portugal — remote, lightly visited, and full of cliff-nesting raptors.",
    highlights: ["Bonelli's eagle", "Black stork", "Egyptian vulture", "Eurasian eagle owl", "Otter"],
    bestSeason: "March–June",
    durationHours: 5,
    tips: "Take the boat trip from Cedillo or Alcántara for cliff-base perspectives you can't get from above.",
    website: "https://parquetajointernacional.juntaex.es/",
  },
  {
    id: "villuercas",
    name: "Geoparque Villuercas-Ibores-Jara",
    type: "mountain",
    lat: 39.5000,
    lng: -5.4000,
    summary: "UNESCO Global Geopark of dramatic ridges and valleys — striking geology paired with raptors and Mediterranean forest.",
    highlights: ["Cinereous vulture", "Bonelli's eagle", "Iberian wolf (very rare)", "Otter", "Mediterranean forest mammals"],
    bestSeason: "Spring and autumn",
    durationHours: 6,
    tips: "Base in Guadalupe (the monastery is a UNESCO site too). The Risco de la Villuerca summit road gives panoramic raptor views.",
    website: "https://geoparquevilluercas.es/",
  },
  {
    id: "sierra-gata",
    name: "Sierra de Gata",
    type: "mountain",
    lat: 40.3000,
    lng: -6.6500,
    summary: "Northern mountain range with chestnut woods, traditional villages and atlantic-influenced wildlife.",
    highlights: ["Black stork", "Cinereous vulture", "Iberian wolf (rare)", "Black woodpecker", "Bonelli's eagle"],
    bestSeason: "May–October",
    durationHours: 6,
    tips: "Hike from Trevejo or Robledillo de Gata. Combine wildlife with the unique 'A Fala' linguistic villages.",
    website: "",
  },
  {
    id: "jerte",
    name: "Garganta de los Infiernos / Valle del Jerte",
    type: "mountain",
    lat: 40.2000,
    lng: -5.7500,
    summary: "Dramatic granite gorge with natural pools, in the Jerte valley famous for its million cherry trees in bloom.",
    highlights: ["Otter", "Dipper", "Grey wagtail", "Iberian green woodpecker", "Cherry blossom (late March)"],
    bestSeason: "Late March–April for cherry blossom; May–September for hiking",
    durationHours: 4,
    tips: "The Los Pilones natural pools trail is the classic hike. Park early at the Garganta de los Infiernos visitor centre.",
    website: "",
  },
];

// Haversine distance in km
function distanceKm(a, b) {
  const R = 6371;
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h = Math.sin(dLat / 2) ** 2 + Math.sin(dLng / 2) ** 2 * Math.cos(lat1) * Math.cos(lat2);
  return Math.round(2 * R * Math.asin(Math.sqrt(h)));
}

// Annotate each site with distance from base
SITES.forEach((s) => { s.distanceKm = distanceKm(BASE, s); });
